import type { TenantMembership } from "./entities"
import { membershipLiveness } from "./effective-state"
import { checkSession, rotateSession, type Rotation, type ServerSession } from "./session"

/**
 * GE-042-006 — moving a person from one tenant to another, mid-session.
 *
 * A session is bound to exactly one tenant: `checkSession` refuses one presented
 * against a different `tenantId` with `WRONG_TENANT`. That makes a tenant switch
 * something other than a preference change. The session in the browser cannot
 * serve the new tenant at all, so the switch must either issue a new session or
 * rotate the existing one — and rotating is right, because the person has not
 * re-authenticated and the absolute clock should not restart.
 *
 * Three things have to happen together, and each is a real failure on its own:
 *
 *   1. **Revalidate.** Membership of the target is proved from live memberships
 *      at the moment of the switch, not from whatever list the browser was sent
 *      when the page rendered. That list can be minutes old, and the interval
 *      between rendering a switcher and clicking it is exactly when somebody
 *      gets suspended.
 *   2. **Rotate.** A new session id, for the same reason authentication rotates
 *      one: the identifier that was valid for the old tenant stops working.
 *      Carrying it across would leave one identifier authoritative in two
 *      tenants, which is the property the tenant binding exists to deny.
 *   3. **Rebind.** The new session names the new tenant. A rotation that
 *      forgot this would produce a fresh id still bound to the tenant the
 *      person just left.
 */

export type SwitchRefusal =
  /** The session presenting the switch is not usable. */
  | "SESSION_NOT_LIVE"
  /** No live membership of the target tenant. */
  | "NOT_A_MEMBER"
  /** Already acting there. */
  | "ALREADY_ACTIVE"

export interface SwitchRefused {
  ok: false
  reason: SwitchRefusal
  detail: string
}

export interface SwitchAccepted {
  ok: true
  rotation: Rotation
  /**
   * Cached renders belonging to the previous tenant, which must not be served
   * to the new one. Stated as an outcome rather than left to the caller: a
   * switch that rotates the session and leaves the old tenant's pages in a
   * cache has moved the person and not the page.
   */
  invalidatesCachedRenders: true
}

export type SwitchOutcome = SwitchAccepted | SwitchRefused

export interface SwitchRequest {
  /** The session presenting the switch. */
  session: ServerSession | null
  /** Every membership the person has, live or not. Liveness is decided here. */
  memberships: readonly TenantMembership[]
  targetTenantId: string
  /** The new identifiers. Generated by the caller, which owns the RNG. */
  next: { sessionId: string; csrfToken: string }
  at: Date
}

/**
 * Decide a tenant switch.
 *
 * Refusals are named rather than collapsed into `false`, because they need
 * different answers: a dead session means sign in again, and no membership
 * means ask somebody for access. A single `false` produces one error page for
 * both, and the person who was suspended is told to sign in again — repeatedly,
 * successfully, and with no effect.
 */
export function planTenantSwitch(request: SwitchRequest): SwitchOutcome {
  const { session, memberships, targetTenantId, next, at } = request

  // The session is checked against the tenant it currently claims, not the
  // target: against the target it would always read WRONG_TENANT, which is the
  // very condition this function exists to resolve.
  const current = checkSession(session, { tenantId: session?.tenantId ?? "", at })
  if (!current.live || !session) {
    return {
      ok: false,
      reason: "SESSION_NOT_LIVE",
      detail: "This session cannot be used to switch tenants. Sign in again.",
    }
  }

  if (session.tenantId === targetTenantId) {
    // Not an error the person caused, but rotating here would hand out a new
    // session id for a double-click. Rotation is not free: the old id stops
    // working, so a rotation racing another request logs somebody out.
    return {
      ok: false,
      reason: "ALREADY_ACTIVE",
      detail: "Already acting in this organization.",
    }
  }

  const live = memberships.some(
    (membership) =>
      membership.personId === session.personId &&
      membership.tenantId === targetTenantId &&
      membershipLiveness(membership, at).live,
  )
  if (!live) {
    return {
      ok: false,
      reason: "NOT_A_MEMBER",
      detail: "You do not have access to this organization. An administrator can grant it.",
    }
  }

  const rotation = rotateSession(session, {
    sessionId: next.sessionId,
    csrfToken: next.csrfToken,
    reason: "PRIVILEGE_CHANGE",
    at,
  })

  return {
    ok: true,
    rotation: {
      // Rebound to the target. `rotateSession` spreads the old session, so
      // without this the new id would still be bound to the old tenant and
      // every request after the switch would fail WRONG_TENANT.
      session: { ...rotation.session, tenantId: targetTenantId },
      previous: rotation.previous,
    },
    invalidatesCachedRenders: true,
  }
}
