/**
 * Emits one event every 30 minutes naming the Bible authorities to re-read from
 * disk, and flags any that are NEW or CHANGED since the last tick.
 *
 * The point is not the heartbeat. It is that a summary of a Bible drifts from
 * the Bible: paraphrase loses the clause that decides the edge case, and a
 * requirement recalled from memory is a requirement nobody checked. So the
 * event carries the file list and the reason to open them, never the content —
 * reading is the work, and this only makes it fall due.
 *
 * It also detects uploads. New authority documents keep arriving, and a
 * document nobody noticed is a domain nobody implements, so a changed SHA is
 * reported loudly rather than folded into the routine line.
 */
import { createHash } from 'node:crypto'
import { readdirSync, readFileSync, statSync } from 'node:fs'
import { join, relative } from 'node:path'

const ROOT = process.argv[2] || process.cwd()
const EVERY_MS = Number(process.argv[3] || 30 * 60 * 1000)

/** Anything that reads like an authority, not a fixed filename list. */
const MARKERS = [/\bBible\b/i, /Master[_ ]Prompt/i, /Implementation[_ ]Extension/i, /ARCHITECTURE/i, /REVIEW-FINDINGS/i, /Global[_ ]Engine/i, /Execution[_ ]Prompt/i]
const SKIP = new Set(['node_modules', '.git', '.next', 'dist', 'build', 'coverage', '.turbo'])

function walk(dir, out = []) {
  let entries
  try {
    entries = readdirSync(dir, { withFileTypes: true })
  } catch {
    return out
  }
  for (const e of entries) {
    if (SKIP.has(e.name)) continue
    const full = join(dir, e.name)
    if (e.isDirectory()) walk(full, out)
    else if (/\.(md|yaml|yml)$/i.test(e.name)) out.push(full)
  }
  return out
}

function authorities() {
  return walk(ROOT)
    .filter((f) => {
      const rel = relative(ROOT, f)
      if (MARKERS.some((m) => m.test(rel))) return true
      // Cheap content sniff for a document that does not announce itself in its
      // name but carries requirement ids.
      try {
        if (statSync(f).size > 4_000_000) return false
        const head = readFileSync(f, 'utf8').slice(0, 4000)
        return /\b[A-Z]{2,8}-\d{3}-\d{3}\b/.test(head)
      } catch {
        return false
      }
    })
    .sort()
}

/**
 * Files that carry requirement ids but are not authorities.
 *
 * Ledgers are appended to by the agents doing the work and `ownership.md` is
 * regenerated by the platform suite, so both change constantly. Reporting them
 * as CHANGED buries the one event this exists to surface — a Bible that was
 * uploaded or edited — under churn the run caused itself.
 */
const GENERATED = [/execution-ledger\.md$/i, /\/ownership\.md$/i, /-registry\.yaml$/i, /document-graph\.yaml$/i]
const isGenerated = (rel) => GENERATED.some((r) => r.test(rel))

const seen = new Map()
let tick = 0

function sweep() {
  tick += 1
  const files = authorities()
  const fresh = []
  const changed = []
  for (const f of files) {
    let sha
    try {
      sha = createHash('sha256').update(readFileSync(f)).digest('hex').slice(0, 12)
    } catch {
      continue
    }
    const rel = relative(ROOT, f).replace(/\\/g, '/')
    const prev = seen.get(rel)
    if (prev === undefined) {
      // A brand-new file is worth announcing even if it is generated — a ledger
      // that did not exist is a domain that just started being worked.
      if (tick > 1) fresh.push(rel)
    } else if (prev !== sha && !isGenerated(rel)) {
      changed.push(rel)
    }
    seen.set(rel, sha)
  }

  for (const f of fresh) console.log(`BIBLE NEW: ${f} — a document that was not here last tick. Read it fully and import its requirements.`)
  for (const f of changed) console.log(`BIBLE CHANGED: ${f} — content moved since last tick. Re-read it; anything decided from the old text is unverified.`)

  if (tick === 1) {
    console.log(`BIBLE WATCH armed: ${files.length} authority documents under ${ROOT}. Re-read fires every ${Math.round(EVERY_MS / 60000)} min.`)
    return
  }
  console.log(
    `BIBLE RE-READ due (tick ${tick}): open the ${files.length} authorities FROM DISK, not from memory or summary. ` +
      `Where PLATFORM-ARCHITECTURE and REVIEW-FINDINGS disagree, the review wins. ` +
      `Then reconcile docs/architecture/capability-completeness-registry.yaml against what you just read.`,
  )
}

sweep()
setInterval(sweep, EVERY_MS)
