/**
 * ANL-000-004 — every `ANL-*` requirement the Analytics Bible states is in the
 * canonical execution ledger, and in the document graph that resolves it back
 * to the Bible.
 *
 * Why a per-family guard when `document-graph.test.mjs` already ratchets a
 * global unimported count. Its sibling `wrk-requirements-are-imported.test.mjs`
 * records the three holes that count cannot see, and every one of them applies
 * here: a row filed in ANOTHER domain's ledger still counts as imported while
 * the domain that owns it has nothing to work; an INVENTED id inflates a
 * denominator nobody re-derives; and a DUPLICATED id is two statuses of which
 * `tools/loop/next-batch.mjs` reads whichever the parser saw last.
 *
 * The fourth hole is the one this requirement's own wording names — "the
 * CANONICAL ledger". The registry records a `ledger:` field per requirement, and
 * that field, not the presence of a row somewhere, is what a reader follows to
 * find the decision. So it is checked directly.
 *
 * Nothing here is read from a hard-coded path except the ledger this family
 * owns: the Bible is opened at the canonical path the graph records for it, so a
 * rename the graph knows about cannot make this pass from a file the graph does
 * not consider authoritative.
 *
 * Plain `node --test` — `npm run test:platform` has no TypeScript and no jest
 * globals.
 */
import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'
import { test } from 'node:test'

import {
  GRAPH_PATH,
  ROOT,
  buildRegistry,
  classify,
  importedIds,
  ledgerStatuses,
  requirementsIn,
} from '../../tools/document-graph.mjs'

const read = (p) => fs.readFileSync(path.join(ROOT, p), 'utf8').replace(/\r\n/g, '\n')

const ANL_LEDGER = 'docs/implementation/analytics-reporting-execution-ledger.md'
const GRAPH_ID = 'tenure-enterprise-analytics-reporting-and-visualization-cloud-claude-bible-v1-0'

/**
 * The graph's own record of the Analytics Bible.
 *
 * Read with a small block reader rather than a YAML parser, as the WRK sibling
 * does and for the same reason: this repository ships no YAML dependency, and
 * the shape is two levels deep and generated by a tool in the same directory.
 */
function graphEntry() {
  const text = read(GRAPH_PATH)
  const marker = `  - id: "${GRAPH_ID}"`
  const at = text.indexOf(marker)
  assert.notEqual(
    at,
    -1,
    `${GRAPH_PATH} has no entry for the Analytics Bible. A requirement register nothing can ` +
      `resolve back to an authority is a list, not a graph.`,
  )
  const rest = text.slice(at + marker.length)
  const end = rest.indexOf('\n  - id:')
  const block = end === -1 ? rest : rest.slice(0, end)
  const value = (key) => {
    const m = new RegExp(`^\\s{4}${key}:\\s*"?([^"\\n]*)"?\\s*$`, 'm').exec(block)
    return m ? m[1].trim() : null
  }
  return {
    canonicalPath: value('canonical_path'),
    role: value('role'),
    statesRequirements: Number(value('states_requirements')),
    prefixes: [...block.matchAll(/^\s{6}- (\w+)\s*$/gm)].map((m) => m[1]),
  }
}

/**
 * The `ANL-*` requirements the Bible states, in the graph's own reading of it.
 *
 * `requirementsIn` rather than a local regex, deliberately: two parsers of one
 * document will disagree, and the loop acts on that one's answer.
 */
function stated() {
  return requirementsIn(read(graphEntry().canonicalPath))
    .map((r) => r.id)
    .filter((id) => id.startsWith('ANL-'))
    .sort()
}

/** Every `ANL-*` id the ledger carries, in file order, with repeats. */
export function ledgerIds(text) {
  const out = []
  for (const line of text.split('\n')) {
    const m = /^- \[[ xX]\] \*\*(ANL-[A-Z0-9-]+)\*\*/.exec(line)
    if (m) out.push(m[1])
  }
  return out
}

test('the document graph registers the Analytics Bible as an authority for ANL', () => {
  const entry = graphEntry()
  assert.ok(
    entry.canonicalPath && fs.existsSync(path.join(ROOT, entry.canonicalPath)),
    `the graph's canonical_path for the Analytics Bible does not exist: ${entry.canonicalPath}`,
  )
  assert.equal(entry.role, 'authority')
  assert.ok(
    entry.prefixes.includes('ANL'),
    `the graph does not record the ANL prefix against the Bible that states it (${entry.prefixes.join(', ')})`,
  )
})

test('the Analytics Bible still states the requirements this pins', () => {
  const expected = stated()
  assert.equal(
    expected.length,
    27,
    `The Analytics Bible states ${expected.length} ANL requirements, not 27. If one was genuinely ` +
      `added or removed, import it and change this number in the same commit — a count that ` +
      `follows the document is not a check.`,
  )
})

test('the graph and the Bible agree on how many requirements it states', () => {
  // A staleness check with teeth: a graph regenerated before the Bible changed,
  // or not regenerated after, gives the loop a denominator that no longer
  // matches the spec.
  assert.equal(graphEntry().statesRequirements, stated().length)
})

test('every ANL requirement the Bible states has a row in the analytics ledger', () => {
  const present = new Set(ledgerIds(read(ANL_LEDGER)))
  assert.deepEqual(
    stated().filter((id) => !present.has(id)),
    [],
    `An ANL requirement stated by the Bible has no row in ${ANL_LEDGER}. A requirement in no ` +
      `execution document is not failing — it is invisible, and invisible reads exactly like done.`,
  )
})

test('the analytics ledger invents no requirement and repeats none', () => {
  const expected = new Set(stated())
  const rows = ledgerIds(read(ANL_LEDGER))

  assert.deepEqual(
    rows.filter((id) => !expected.has(id)).sort(),
    [],
    `${ANL_LEDGER} carries an ANL id the Bible does not state. An invented row is a denominator ` +
      `nobody can re-derive.`,
  )

  const seen = new Set()
  const duplicated = []
  for (const id of rows) {
    if (seen.has(id)) duplicated.push(id)
    seen.add(id)
  }
  assert.deepEqual(
    duplicated,
    [],
    `${ANL_LEDGER} states an id twice. Two rows are two statuses, and the loop reads whichever ` +
      `the parser saw last.`,
  )
})

test('no other ledger claims an ANL requirement', () => {
  // Not a missing row — a row in the WRONG PLACE. The global unimported count is
  // a union over every ledger, so an ANL row filed under another domain reads as
  // imported while the domain that owns it has nothing to work.
  const ledger = ledgerStatuses()
  const misfiled = stated()
    .filter((id) => {
      const source = ledger.get(id)?.source_ledger
      return source !== undefined && source !== ANL_LEDGER
    })
    .sort()

  assert.deepEqual(misfiled, [], `An ANL requirement is filed in a ledger other than ${ANL_LEDGER}.`)
})

test('the registry sends a reader of any ANL requirement to the analytics ledger', () => {
  // The half the WRK sibling does not check, and the half this requirement's
  // wording actually names: the registry's `ledger:` field is what a reader
  // follows to find the decision, and a null there is a requirement whose row
  // exists and cannot be found from the register.
  const rows = buildRegistry(classify(), ledgerStatuses(), importedIds()).filter((r) => r.prefix === 'ANL')
  const unrouted = rows.filter((r) => r.ledger !== ANL_LEDGER).map((r) => `${r.id} → ${r.ledger}`)
  assert.deepEqual(
    unrouted,
    [],
    `The registry routes an ANL requirement somewhere other than ${ANL_LEDGER}.`,
  )
})

test('the generated registry owns exactly the ANL requirements the Bible states', () => {
  const expected = stated()
  const canonical = graphEntry().canonicalPath
  const rows = buildRegistry(classify(), ledgerStatuses(), importedIds()).filter((r) => r.prefix === 'ANL')

  assert.deepEqual(
    rows.map((r) => r.id).sort(),
    expected,
    'The capability registry must own exactly the ANL requirements stated by the Analytics Bible.',
  )
  assert.deepEqual(
    rows.filter((r) => r.source_document !== canonical).map((r) => r.id),
    [],
    'Every ANL registry row must resolve back to the Analytics Bible at its canonical path.',
  )
  assert.deepEqual(
    rows.filter((r) => !r.imported).map((r) => r.id),
    [],
    'An ANL requirement is in the registry and marked unimported.',
  )
})

test('the detector reads ids rather than counting lines', () => {
  // Assembled here rather than read from the tree, so the parser is proven
  // against a shape it has never seen: a checked row, an unchecked row, another
  // family's row, and prose that mentions an id without stating it.
  const sample = [
    '- [x] **ANL-000-001** — done',
    '- [ ] **ANL-000-004** — not done',
    '- [ ] **WRK-000-001** — another domain',
    '  - Reason: see ANL-000-001 for the inventory',
    '- [ ] **ANL-GATE-000** — a gate',
  ].join('\n')

  assert.deepEqual(ledgerIds(sample), ['ANL-000-001', 'ANL-000-004', 'ANL-GATE-000'])
})
