import assert from "node:assert/strict"
import fs from "node:fs"
import path from "node:path"
import { fileURLToPath } from "node:url"
import { test } from "node:test"

/**
 * IER-120-004 — "Derive UI navigation safely without using it as enforcement."
 *
 * The derivation half is already built and has real callers:
 * `apps/web/src/lib/authz/navigation-capabilities.ts` asks `decide()` from
 * `@tenure/authorization` for each `NAV_CAPABILITIES` value, and
 * `(app)/layout.tsx:61` and `api/me/route.ts:58` are what call it. Nothing was
 * checking the second half, and `packages/platform-config/src/modules.ts:270`
 * asserts it in a comment — "Navigation is not authorization. Hiding a link does
 * not protect a route, and every route still checks for itself" — which is a
 * claim, not a control.
 *
 * The claim is FALSE today, and this file is what found it. `/reports` is
 * contributed by the `budgeting` manifest with
 * `requiresCapability: "finance.report.read"`, and `/(app)/reports` carries
 * `session` + `tenant` and no capability guard. So for that one page the menu
 * entry IS the access control: somebody who does not hold the capability sees no
 * link and can open the URL.
 *
 * ## Why this ships with the breach named rather than green
 *
 * The same shape as `UNAUTHORIZED_MUTATORS` in
 * `tests/security/every-path-authorizes.test.mjs`. `EXEMPT` is not permission —
 * a route on it that has since gained a capability guard fails this test too, so
 * the list can only shrink, and every future capability-gated nav entry is held
 * to the rule from the day it is added.
 *
 * ## What it reads
 *
 * `docs/architecture/entry-points.md`, generated by
 * `tools/entry-point-inventory.mjs`, which walks the layout chain — so a page
 * guarded by a layout above it is correctly reported as guarded.
 * `npm run test:platform` regenerates and compares it, so it cannot drift. A
 * second guard-attribution implementation here would be a second answer to the
 * same question, and the one nobody is looking at is the one that goes wrong.
 */

const HERE = path.dirname(fileURLToPath(import.meta.url))
const ROOT = path.resolve(HERE, "../..")

const read = (p) => fs.readFileSync(path.join(ROOT, p), "utf8")

/**
 * Capability-gated navigation entries, parsed out of the module catalog.
 *
 * `modules/index.ts` is TypeScript importing `@tenure/module-runtime`, and this
 * suite runs under bare `node --test` with no transform, so the declarations are
 * read as text — the same constraint and the same approach as
 * `tests/architecture/module-objects.test.mjs`. It fails loudly below if the
 * shape it expects has gone.
 */
function gatedNavEntries() {
  const source = read("modules/index.ts")
  const entries = []

  // Each `{ ... }` inside a `navigation: [ ... ]` block. Objects here are flat,
  // so the non-greedy run to the next `}` is the whole entry.
  for (const block of source.matchAll(/navigation:\s*\[([\s\S]*?)\n\s*\],/g)) {
    for (const entry of block[1].matchAll(/\{([\s\S]*?)\}/g)) {
      const body = entry[1]
      const capability = /\brequiresCapability:\s*"([^"]+)"/.exec(body)?.[1]
      if (!capability) continue
      entries.push({
        id: /\bid:\s*"([^"]+)"/.exec(body)?.[1] ?? null,
        href: /\bhref:\s*"([^"]+)"/.exec(body)?.[1] ?? null,
        capability,
      })
    }
  }

  return entries
}

/**
 * Routes and their guards, from the generated inventory.
 *
 * Route groups are stripped: Next.js `(app)` is a directory that does not appear
 * in a URL, and the manifest declares the URL.
 */
function inventoryRoutes() {
  const routes = new Map()
  for (const row of read("docs/architecture/entry-points.md").matchAll(
    /^\|\s*`([^`]+)`\s*\|\s*([^|]*)\|\s*([^|]*)\|\s*([^|]*)\|/gm,
  )) {
    const route = row[1].trim()
    if (!route.startsWith("/")) continue
    const url = route.replace(/\/\([^)]+\)/g, "") || "/"
    const guards = [...row[4].matchAll(/`([^`]+)`/g)].map((g) => g[1])
    // A URL can be listed once as a page; if it appears twice, the union is the
    // honest reading — every listing of it is a way in.
    const existing = routes.get(url)
    routes.set(url, existing ? [...new Set([...existing, ...guards])] : guards)
  }
  return routes
}

/**
 * Capability-gated nav entries whose route enforces nothing but membership.
 *
 * MAY ONLY SHRINK. Each names the route, the capability the menu claims is
 * required, and what the route actually checks instead.
 */
const EXEMPT = new Map([
  [
    "/reports",
    "The `budgeting` manifest hides this entry behind `finance.report.read`; `/(app)/reports` checks " +
      "`session` + `tenant` and then `ctx.institutionRoles[0]` — an institution membership, not the " +
      "capability. Today the two coincide, because `navigation-capabilities.ts` maps all three institution " +
      "roles to both nav capabilities. That is a coincidence of the current mapping and not enforcement: " +
      "the moment Advisor is narrowed, or a tenant runs without the budgeting module, the menu hides the " +
      "link and the URL still answers. Closing it is a capability check on the page, which is an access " +
      "change to a live surface and belongs to a change that can be run against a database.",
  ],
])

test("every capability-gated navigation entry names a route the inventory knows", () => {
  const entries = gatedNavEntries()
  assert.ok(entries.length > 0, "no capability-gated navigation entries were parsed — the catalog shape has drifted")

  const routes = inventoryRoutes()
  assert.ok(routes.size > 20, `only ${routes.size} routes parsed out of the inventory — the table shape has drifted`)

  const missing = entries.filter((entry) => entry.href && !routes.has(entry.href))
  assert.deepEqual(
    missing.map((entry) => `${entry.id} -> ${entry.href}`),
    [],
    "these menu entries point at a route no entry point serves; the menu would offer a dead link",
  )
})

test("a route the menu hides behind a capability checks that capability itself", () => {
  const routes = inventoryRoutes()
  const offenders = []

  for (const entry of gatedNavEntries()) {
    if (!entry.href || EXEMPT.has(entry.href)) continue
    const guards = routes.get(entry.href) ?? []
    if (!guards.includes("capability")) {
      offenders.push(`${entry.href} (menu requires ${entry.capability}; route guards: ${guards.join(" + ") || "none"})`)
    }
  }

  assert.deepEqual(
    offenders,
    [],
    `these routes are protected only by not being in the menu:\n  ${offenders.join("\n  ")}\n` +
      `Hiding a link is not authorization — the URL is in the page source, in a bookmark and in a browser ` +
      `history. Add a capability guard to the route, or name it in EXEMPT with what it checks instead.`,
  )
})

test("the exemption list only shrinks, and cannot outlive the thing it excuses", () => {
  const routes = inventoryRoutes()
  const gated = new Set(gatedNavEntries().map((entry) => entry.href))

  for (const [href, why] of EXEMPT) {
    assert.ok(gated.has(href), `${href} is exempt but no capability-gated menu entry points at it`)
    assert.ok(why.length > 120, `${href} is exempt without a real reason`)
    const guards = routes.get(href) ?? []
    assert.ok(
      !guards.includes("capability"),
      `${href} now carries a capability guard. Remove it from EXEMPT — a list nobody prunes stops being a debt ` +
        `register and becomes a permission.`,
    )
  }

  // 1 -> 0 is the only direction this is allowed to move.
  assert.equal(EXEMPT.size, 1, "the navigation-as-enforcement exemption list changed size")
})

test("every capability the menu asks for is one the derivation can produce", () => {
  // A menu entry requiring a capability nothing derives is permanently hidden
  // from everybody, which looks exactly like a permissions bug and is reported
  // as one. The link is the reason `NAV_CAPABILITIES` exists rather than the
  // strings being written twice.
  const derived = new Set(
    [...read("apps/web/src/lib/authz/navigation-capabilities.ts").matchAll(/^\s*\w+:\s*"([^"]+)",$/gm)].map(
      (m) => m[1],
    ),
  )
  assert.ok(derived.size > 0, "no capabilities parsed out of NAV_CAPABILITIES — its shape has drifted")

  const undeliverable = gatedNavEntries()
    .filter((entry) => !derived.has(entry.capability))
    .map((entry) => `${entry.id} requires ${entry.capability}`)

  assert.deepEqual(
    undeliverable,
    [],
    `these menu entries require a capability the navigation derivation never asks the engine about, so they ` +
      `are hidden from everyone permanently`,
  )
})

test("the derivation asks the authorization engine rather than counting rows", () => {
  // Anchored on the CALL, not the import: `indexOf("decide")` finds the import
  // line and would stay true if the body stopped calling it. That use-vs-mention
  // failure is recorded twice already in tests/security.
  const source = read("apps/web/src/lib/authz/navigation-capabilities.ts").replace(/^import[\s\S]*?from .*$/gm, "")
  assert.match(
    source,
    /\bdecide\(\s*world/,
    "navigation-capabilities.ts no longer calls decide() on a world — the menu is being derived some other way",
  )
})

test("nothing that enforces imports the navigation derivation", () => {
  // The inverse direction, and the cheaper mistake to make: a route guard that
  // reuses the menu's capability set inherits the menu's purpose, which is to be
  // permissive enough that nobody is confused by a missing link.
  //
  // Matched on the IMPORT, with comments stripped first. `rbac.ts` names
  // `navigation-capabilities.ts` in a docblock explaining that both build their
  // world the same way; a substring check read that as a dependency and failed.
  // Prose about a thing is not a use of it — the same trap
  // `tests/security/email-is-not-a-key.test.mjs` records twice.
  const IMPORTS_NAV = /^\s*import[\s\S]*?from\s+["'][^"']*navigation-capabilities["']/m
  const ENFORCING = ["apps/web/src/lib/admin/guard.ts", "apps/web/src/lib/rbac.ts"]

  for (const file of ENFORCING) {
    const full = path.join(ROOT, file)
    assert.ok(fs.existsSync(full), `${file} is guarded here but does not exist`)
    const source = fs
      .readFileSync(full, "utf8")
      .replace(/\/\*[\s\S]*?\*\//g, "")
      .replace(/(^|[^:])\/\/.*$/gm, "$1")
    assert.ok(
      !IMPORTS_NAV.test(source),
      `${file} imports the navigation derivation. Navigation is filtered for usefulness; enforcement is not.`,
    )
  }

  // And the check can still see one. A guard that can only pass is not a guard,
  // and this one just passed for the wrong reason once already.
  assert.ok(
    IMPORTS_NAV.test('import { navigationCapabilitiesFor } from "@/lib/authz/navigation-capabilities"'),
    "the import detector no longer matches a real import of the navigation derivation",
  )
})
