/**
 * PLN-000-004 — every `PLN-*` item is in the canonical ledger, in the document
 * graph, and under the sentence the Bible actually states.
 *
 * The global ratchet in `document-graph.test.mjs` counts requirements reaching
 * NO execution document. That answers "has a whole Bible been dropped" and
 * nothing narrower: a `PLN-030-002` row filed in another domain's ledger still
 * decrements it, an invented `PLN-050-009` inflates a denominator nobody
 * re-derives, and a duplicated id gives the loop two statuses of which
 * `ledgerStatuses()` keeps whichever the parser saw last. Its WRK and INT
 * siblings record those three holes and close them per family; this file closes
 * them for PLN.
 *
 * It then adds the half none of the siblings check, and the half that decides
 * whether "imported" means anything: **the row's own title must be the Bible's
 * own sentence.** An id can be present, unique, correctly filed and still be
 * working on a different requirement — `PLN-030-001` retitled from "spreading,
 * allocations and top-down/bottom-up reconciliation" to "spreading" is a row
 * that will one day be ticked, and the thing it proves will not be the thing
 * the authority asked for. Nothing else in the programme compares those two
 * strings. `tools/import-requirements.mjs` wrote them equal once; only a check
 * keeps them equal, because the ledger is edited by hand for years afterwards
 * and the Bible is not edited at all.
 *
 * Titles are compared after collapsing whitespace, because the ledger is
 * hard-wrapped and the Bible is not, and a line break is not a change of
 * meaning. Everything else — punctuation, backticks, the trailing full stop —
 * is compared verbatim, since "Implement financial planning and Finance
 * publication/reconciliation" and "Implement financial planning" differ in
 * exactly the way this is looking for.
 *
 * A qualifier inside the bold run is allowed: `**PLN-030-001 (the spreading
 * half)**` is how one requirement is closed across several rows, and
 * `ledgerStatuses()` already parses that shape. When it appears, the qualifier
 * is dropped and the remaining title is still held to the Bible's sentence, so
 * splitting a requirement across rows cannot be used to reword it.
 *
 * The Bible is read at the canonical path the GRAPH records, never at a
 * hard-coded string, so a rename the graph knows about cannot make this pass
 * from a file the graph does not consider authoritative.
 *
 * Plain `node --test` — this directory is run by `npm run test:platform`, which
 * has no TypeScript and no jest globals.
 */
import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'
import { test } from 'node:test'

import {
  GRAPH_PATH,
  ROOT,
  buildRegistry,
  classify,
  importedIds,
  ledgerStatuses,
  requirementsIn,
} from '../../tools/document-graph.mjs'

const read = (p) => fs.readFileSync(path.join(ROOT, p), 'utf8').replace(/\r\n/g, '\n')

const PLN_LEDGER = 'docs/implementation/planning-epm-execution-ledger.md'
const GRAPH_ID = 'tenure-planning-epm-and-decision-cloud-claude-bible-v1-0'

/**
 * How many `PLN-*` requirements the Bible states.
 *
 * A pinned literal, not a count read from the file. A count that follows the
 * document is not a check: it agrees with whatever the document says today,
 * including after a section was deleted. If a requirement is genuinely added or
 * removed, import it and change this number in the same commit.
 */
const STATED_COUNT = 27

/**
 * The graph's own record of the Planning Bible.
 *
 * Read out of the generated YAML with a small block reader rather than a YAML
 * parser: this repository ships no YAML dependency, and the shape is two levels
 * deep and generated by a tool in this same directory.
 */
function graphEntry() {
  const text = read(GRAPH_PATH)
  const marker = `  - id: "${GRAPH_ID}"`
  const at = text.indexOf(marker)
  assert.notEqual(
    at,
    -1,
    `${GRAPH_PATH} has no entry for the Planning, EPM and Decision Cloud Bible. A requirement ` +
      `register nothing can resolve back to an authority is a list, not a graph.`,
  )
  const rest = text.slice(at + marker.length)
  const end = rest.indexOf('\n  - id:')
  const block = end === -1 ? rest : rest.slice(0, end)
  const value = (key) => {
    const m = new RegExp(`^\\s{4}${key}:\\s*"?([^"\\n]*)"?\\s*$`, 'm').exec(block)
    return m ? m[1].trim() : null
  }
  return {
    canonicalPath: value('canonical_path'),
    role: value('role'),
    statesRequirements: Number(value('states_requirements')),
    prefixes: [...block.matchAll(/^\s{6}- (\w+)\s*$/gm)].map((m) => m[1]),
  }
}

/**
 * The `PLN-*` requirements the Bible states, in the graph's own reading of it.
 *
 * `requirementsIn` rather than a local regex, deliberately: two parsers of one
 * document will disagree, and the loop acts on that one's answer.
 */
function stated() {
  return requirementsIn(read(graphEntry().canonicalPath))
    .filter((r) => r.id.startsWith('PLN-'))
    .sort((a, b) => (a.id < b.id ? -1 : a.id > b.id ? 1 : 0))
}

/**
 * Every `PLN-*` row the ledger opens, in file order, with repeats, each with the
 * title it was written under.
 *
 * The id pattern ends at `\b` and the qualifier is captured separately, for the
 * reason `ledgerStatuses()` documents at length: seventeen rows elsewhere in the
 * programme write `**GE-042-004 (the adapter half)**`, and a pattern demanding
 * the closing asterisks straight after the digits matched none of them.
 */
export function ledgerRows(text) {
  const out = []
  for (const line of text.split('\n')) {
    const m = /^- \[[ xX]\] \*\*(PLN-\d{3}-\d{3}|PLN-GATE-\d+)\b([^*]*)\*\*(?:\s*—\s*(.*))?$/.exec(line)
    if (!m) continue
    out.push({ id: m[1], qualifier: m[2].trim(), title: (m[3] ?? '').replace(/\s+/g, ' ').trim() })
  }
  return out
}

test('the document graph registers the Planning Bible as an authority for PLN', () => {
  const entry = graphEntry()
  assert.ok(
    entry.canonicalPath && fs.existsSync(path.join(ROOT, entry.canonicalPath)),
    `the graph's canonical_path for the Planning Bible does not exist: ${entry.canonicalPath}`,
  )
  assert.equal(entry.role, 'authority')
  assert.ok(
    entry.prefixes.includes('PLN'),
    `the graph does not record the PLN prefix against the Bible that states it (${entry.prefixes.join(', ')})`,
  )
})

test('the Planning Bible still states the requirements this pins', () => {
  const expected = stated()
  assert.equal(
    expected.length,
    STATED_COUNT,
    `The Planning Bible states ${expected.length} PLN requirements, not ${STATED_COUNT}. If one ` +
      `was genuinely added or removed, import it and change this number in the same commit — a ` +
      `count that follows the document is not a check.`,
  )
})

test('the graph and the Planning Bible agree on how many requirements it states', () => {
  // A staleness check with teeth: a graph regenerated before the Bible changed,
  // or not regenerated after, hands the loop a denominator that no longer
  // matches the spec.
  assert.equal(graphEntry().statesRequirements, stated().length)
})

test('every PLN requirement the Bible states has a row in the planning ledger', () => {
  const present = new Set(ledgerRows(read(PLN_LEDGER)).map((r) => r.id))
  assert.deepEqual(
    stated()
      .map((r) => r.id)
      .filter((id) => !present.has(id)),
    [],
    `A PLN requirement stated by the Bible has no row in ${PLN_LEDGER}. A requirement in no ` +
      `execution document is not failing — it is invisible, and invisible reads exactly like done.`,
  )
})

test('the planning ledger invents no requirement and repeats none', () => {
  const expected = new Set(stated().map((r) => r.id))
  const rows = ledgerRows(read(PLN_LEDGER))

  assert.deepEqual(
    rows
      .map((r) => r.id)
      .filter((id) => !expected.has(id))
      .sort(),
    [],
    `${PLN_LEDGER} carries a PLN id the Bible does not state. An invented row is a denominator ` +
      `nobody can re-derive.`,
  )

  const seen = new Set()
  const duplicated = []
  for (const { id, qualifier } of rows) {
    // A qualified row is the one legitimate repeat: `**PLN-030-001 (the
    // spreading half)**` closes one requirement across several rows on purpose.
    // Two BARE rows for one id are two statuses, and the loop reads whichever
    // the parser saw last.
    if (seen.has(id) && qualifier === '') duplicated.push(id)
    if (qualifier === '') seen.add(id)
  }
  assert.deepEqual(
    duplicated,
    [],
    `${PLN_LEDGER} opens an unqualified row for the same id twice. Two rows are two statuses.`,
  )
})

test('every planning ledger row is titled with the sentence the Bible states', () => {
  const bible = new Map(stated().map((r) => [r.id, r.statement.replace(/\s+/g, ' ').trim()]))
  const wrong = []
  for (const row of ledgerRows(read(PLN_LEDGER))) {
    const expected = bible.get(row.id)
    if (expected === undefined) continue // covered by the invents-nothing test
    if (row.title !== expected) wrong.push({ id: row.id, expected, found: row.title })
  }
  assert.deepEqual(
    wrong,
    [],
    `A row in ${PLN_LEDGER} is titled with something other than the requirement's own sentence. ` +
      `A retitled row is a requirement quietly replaced by an easier one: it will be ticked, and ` +
      `what it proves will not be what the authority asked for.`,
  )
})

test('no other ledger claims a PLN requirement', () => {
  // Not a missing row — a row in the WRONG PLACE. The global unimported count is
  // a union over every ledger, so a PLN row filed under another domain reads as
  // imported while the domain that owns it has nothing to work.
  const ledger = ledgerStatuses()
  const misfiled = stated()
    .map((r) => r.id)
    .filter((id) => {
      const source = ledger.get(id)?.source_ledger
      return source !== undefined && source !== PLN_LEDGER
    })
    .sort()

  assert.deepEqual(misfiled, [], `A PLN requirement is filed in a ledger other than ${PLN_LEDGER}.`)
})

test('the generated registry owns exactly the PLN requirements the Bible states', () => {
  const expected = stated().map((r) => r.id)
  const canonical = graphEntry().canonicalPath
  const rows = buildRegistry(classify(), ledgerStatuses(), importedIds()).filter(
    (r) => r.prefix === 'PLN',
  )

  assert.deepEqual(
    rows.map((r) => r.id).sort(),
    expected,
    'The capability registry must own exactly the PLN requirements stated by the Planning Bible.',
  )
  assert.deepEqual(
    rows.filter((r) => r.source_document !== canonical).map((r) => r.id),
    [],
    'Every PLN registry row must resolve back to the Planning Bible at its canonical path.',
  )
})

test('the row detector reads ids and titles rather than counting lines', () => {
  // Assembled here rather than read from the tree, so the parser is proven
  // against shapes it has never seen: a checked row, an unchecked row, a
  // qualified row, a gate, another family's row, and prose that mentions an id
  // without opening a row for it.
  const sample = [
    '- [x] **PLN-000-001** — Inventory current budget/planning/report code and false EPM claims.',
    '- [ ] **PLN-030-001 (the spreading half)** — Implement spreading, allocations and',
    '- [ ] **WRK-000-003** — another domain',
    '  - Reason: see PLN-000-001 for the inventory',
    '- [ ] **PLN-GATE-000** — Multidimensional planning foundation is correct and tenant-safe.',
  ].join('\n')

  assert.deepEqual(ledgerRows(sample), [
    {
      id: 'PLN-000-001',
      qualifier: '',
      title: 'Inventory current budget/planning/report code and false EPM claims.',
    },
    {
      id: 'PLN-030-001',
      qualifier: '(the spreading half)',
      title: 'Implement spreading, allocations and',
    },
    {
      id: 'PLN-GATE-000',
      qualifier: '',
      title: 'Multidimensional planning foundation is correct and tenant-safe.',
    },
  ])
})
