/**
 * WRK-000-003 — every `WRK-*` requirement is in the canonical execution ledger
 * AND in the document graph.
 *
 * The global ratchet in `document-graph.test.mjs` counts requirements that
 * reach NO execution document, and it is the right shape for the question it
 * answers: has a whole Bible been dropped. It is the wrong shape for this one,
 * and its sibling `int-requirements-are-imported.test.mjs` records why — a row
 * that lands in somebody else's ledger still counts as imported, an invented id
 * inflates a denominator nobody re-derives, and a duplicated id means two
 * statuses of which the loop reads whichever the parser saw last.
 *
 * This adds the half that requirement names and the INT sibling does not: the
 * DOCUMENT GRAPH. A ledger holding all 88 rows while the graph has never heard
 * of the Bible that states them is an import into one register, not two, and
 * `tools/loop/next-batch.mjs` would still be working from a document nothing
 * can resolve back to an authority. So the graph's own entry for this Bible is
 * checked too: its canonical path, that it claims the `WRK` prefix, and that
 * the number of requirements it says it states is the number the file states.
 *
 * The Bible is read at its canonical path as the graph records it, never at a
 * hard-coded string, so a rename that the graph knows about cannot make this
 * test pass from a file the graph does not consider authoritative.
 *
 * Plain `node --test` — this directory is run by `npm run test:platform`, which
 * has no TypeScript and no jest globals.
 */
import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'
import { test } from 'node:test'

import {
  GRAPH_PATH,
  ROOT,
  buildRegistry,
  classify,
  importedIds,
  ledgerStatuses,
  requirementsIn,
} from '../../tools/document-graph.mjs'

const read = (p) => fs.readFileSync(path.join(ROOT, p), 'utf8').replace(/\r\n/g, '\n')

const WRK_LEDGER = 'docs/implementation/universal-work-graph-execution-ledger.md'
const GRAPH_ID = 'tenure-universal-work-graph-and-workspace-connector-cloud-claude-bible-v1-0'

/**
 * The graph's own record of the Work Graph Bible.
 *
 * Read out of the generated YAML with a small block reader rather than a YAML
 * parser: this repository ships no YAML dependency, and the shape here is two
 * levels deep and generated by a tool in this same directory.
 */
function graphEntry() {
  const text = read(GRAPH_PATH)
  const marker = `  - id: "${GRAPH_ID}"`
  const at = text.indexOf(marker)
  assert.notEqual(
    at,
    -1,
    `${GRAPH_PATH} has no entry for the Work Graph Bible. A requirement register nothing can ` +
      `resolve back to an authority is a list, not a graph.`,
  )
  const rest = text.slice(at + marker.length)
  const end = rest.indexOf('\n  - id:')
  const block = end === -1 ? rest : rest.slice(0, end)
  const value = (key) => {
    const m = new RegExp(`^\\s{4}${key}:\\s*"?([^"\\n]*)"?\\s*$`, 'm').exec(block)
    return m ? m[1].trim() : null
  }
  return {
    canonicalPath: value('canonical_path'),
    role: value('role'),
    statesRequirements: Number(value('states_requirements')),
    prefixes: [...block.matchAll(/^\s{6}- (\w+)\s*$/gm)].map((m) => m[1]),
  }
}

/**
 * The requirements the Bible states, in the graph's own reading of it.
 *
 * `requirementsIn` rather than a local regex, deliberately: two parsers of one
 * document will disagree, and the loop acts on that one's answer.
 */
function stated() {
  const entry = graphEntry()
  return requirementsIn(read(entry.canonicalPath))
    .map((r) => r.id)
    .filter((id) => id.startsWith('WRK-'))
    .sort()
}

/** Every `WRK-*` id the ledger carries, in file order, with repeats. */
export function ledgerIds(text) {
  const out = []
  for (const line of text.split('\n')) {
    const m = /^- \[[ xX]\] \*\*(WRK-[A-Z0-9-]+)\*\*/.exec(line)
    if (m) out.push(m[1])
  }
  return out
}

test('the document graph registers the Work Graph Bible as an authority for WRK', () => {
  const entry = graphEntry()
  assert.ok(
    entry.canonicalPath && fs.existsSync(path.join(ROOT, entry.canonicalPath)),
    `the graph's canonical_path for the Work Graph Bible does not exist: ${entry.canonicalPath}`,
  )
  assert.equal(entry.role, 'authority')
  assert.ok(
    entry.prefixes.includes('WRK'),
    `the graph does not record the WRK prefix against the Bible that states it (${entry.prefixes.join(', ')})`,
  )
})

test('the Work Graph Bible still states the requirements this pins', () => {
  const expected = stated()
  assert.equal(
    expected.length,
    88,
    `The Work Graph Bible states ${expected.length} WRK requirements, not 88. If a requirement ` +
      `was genuinely added or removed, import it and change this number in the same commit — a ` +
      `count that follows the document is not a check.`,
  )
})

test('the graph and the Bible agree on how many requirements it states', () => {
  // The graph is generated from the Bible, so this is a staleness check with
  // teeth: a graph regenerated before the Bible changed, or not regenerated
  // after, gives the loop a denominator that no longer matches the spec.
  assert.equal(graphEntry().statesRequirements, stated().length)
})

test('every WRK requirement the Bible states has a row in the work-graph ledger', () => {
  const expected = stated()
  const present = new Set(ledgerIds(read(WRK_LEDGER)))

  assert.deepEqual(
    expected.filter((id) => !present.has(id)),
    [],
    `A WRK requirement stated by the Bible has no row in ${WRK_LEDGER}. A requirement in no ` +
      `execution document is not failing — it is invisible, and invisible reads exactly like done.`,
  )
})

test('the work-graph ledger invents no requirement and repeats none', () => {
  const expected = new Set(stated())
  const rows = ledgerIds(read(WRK_LEDGER))

  assert.deepEqual(
    rows.filter((id) => !expected.has(id)).sort(),
    [],
    `${WRK_LEDGER} carries a WRK id the Bible does not state. An invented row is a denominator ` +
      `nobody can re-derive.`,
  )

  const seen = new Set()
  const duplicated = []
  for (const id of rows) {
    if (seen.has(id)) duplicated.push(id)
    seen.add(id)
  }
  assert.deepEqual(
    duplicated,
    [],
    `${WRK_LEDGER} states an id twice. Two rows are two statuses, and the loop reads whichever ` +
      `the parser saw last.`,
  )
})

test('no other ledger claims a WRK requirement', () => {
  // Not a missing row — a row in the WRONG PLACE. The global unimported count
  // is a union over every ledger, so a WRK row filed under another domain reads
  // as imported while the domain that owns it has nothing to work.
  const ledger = ledgerStatuses()
  const misfiled = stated()
    .filter((id) => {
      const source = ledger.get(id)?.source_ledger
      return source !== undefined && source !== WRK_LEDGER
    })
    .sort()

  assert.deepEqual(misfiled, [], `A WRK requirement is filed in a ledger other than ${WRK_LEDGER}.`)
})

test('the generated registry owns exactly the WRK requirements the Bible states', () => {
  const expected = stated()
  const canonical = graphEntry().canonicalPath
  const rows = buildRegistry(classify(), ledgerStatuses(), importedIds()).filter(
    (r) => r.prefix === 'WRK',
  )

  assert.deepEqual(
    rows.map((r) => r.id).sort(),
    expected,
    'The capability registry must own exactly the WRK requirements stated by the Work Graph Bible.',
  )
  assert.deepEqual(
    rows.filter((r) => r.source_document !== canonical).map((r) => r.id),
    [],
    'Every WRK registry row must resolve back to the Work Graph Bible at its canonical path.',
  )
})

test('the detector reads ids rather than counting lines', () => {
  // Assembled here rather than read from the tree, so the parser is proven
  // against a shape it has never seen: a checked row, an unchecked row, a
  // non-WRK row and prose that mentions an id without stating it.
  const sample = [
    '- [x] **WRK-000-002** — done',
    '- [ ] **WRK-000-003** — not done',
    '- [ ] **INT-000-001** — another domain',
    '  - Reason: see WRK-000-002 for the classification',
    '- [ ] **WRK-GATE-000** — a gate',
  ].join('\n')

  assert.deepEqual(ledgerIds(sample), ['WRK-000-002', 'WRK-000-003', 'WRK-GATE-000'])
})
