/**
 * The design token catalog — GENERATED. Do not edit by hand.
 *
 *   node scripts/generate-design-tokens.mjs
 *
 * Emitted from `src/app/globals.css` by `scripts/generate-design-tokens.mjs`,
 * which is where the tiers are decided and where the header of this comment
 * explains why the pipeline exists. `src/lib/a11y/tokens.test.ts` re-runs the
 * generator against the real stylesheet and fails if this file is stale, so the
 * catalog cannot quietly disagree with the CSS the product ships.
 *
 * `TokenName` is the payoff: it is a union over the names below, so a token
 * removed from the stylesheet stops compiling at every call site that named it
 * — `src/components/charts/palette.ts` is the first — instead of resolving to
 * an undeclared custom property at runtime, which is invisible.
 */

export type TokenLayer = "primitive" | "semantic" | "component"

export interface TokenEntry {
  readonly name: string
  readonly layer: TokenLayer
}

/** Every custom property `globals.css` declares, in the tier it belongs to. */
export const TOKENS = [
  { name: "--accent", layer: "semantic" },
  { name: "--accent-hover", layer: "semantic" },
  { name: "--accent-light", layer: "semantic" },
  { name: "--accent-strong", layer: "semantic" },
  { name: "--accent-text", layer: "semantic" },
  { name: "--badge-accent-bg", layer: "component" },
  { name: "--badge-accent-text", layer: "component" },
  { name: "--badge-approved-bg", layer: "component" },
  { name: "--badge-approved-text", layer: "component" },
  { name: "--badge-draft-bg", layer: "component" },
  { name: "--badge-draft-text", layer: "component" },
  { name: "--badge-pending-bg", layer: "component" },
  { name: "--badge-pending-text", layer: "component" },
  { name: "--badge-rejected-bg", layer: "component" },
  { name: "--badge-rejected-text", layer: "component" },
  { name: "--bg-base", layer: "semantic" },
  { name: "--bg-overlay", layer: "semantic" },
  { name: "--bg-subtle", layer: "semantic" },
  { name: "--bg-surface", layer: "semantic" },
  { name: "--border", layer: "semantic" },
  { name: "--border-control", layer: "semantic" },
  { name: "--border-focus", layer: "semantic" },
  { name: "--border-strong", layer: "semantic" },
  { name: "--chart-1", layer: "component" },
  { name: "--chart-2", layer: "component" },
  { name: "--chart-3", layer: "component" },
  { name: "--chart-4", layer: "component" },
  { name: "--chart-5", layer: "component" },
  { name: "--chart-6", layer: "component" },
  { name: "--chart-7", layer: "component" },
  { name: "--chart-8", layer: "component" },
  { name: "--chart-axis", layer: "component" },
  { name: "--chart-grid", layer: "component" },
  { name: "--content-max", layer: "primitive" },
  { name: "--control-h", layer: "primitive" },
  { name: "--control-h-lg", layer: "primitive" },
  { name: "--control-h-sm", layer: "primitive" },
  { name: "--density-gap", layer: "semantic" },
  { name: "--ease-entry", layer: "primitive" },
  { name: "--ease-exit", layer: "primitive" },
  { name: "--error", layer: "semantic" },
  { name: "--error-light", layer: "semantic" },
  { name: "--error-text", layer: "semantic" },
  { name: "--font-display", layer: "primitive" },
  { name: "--font-sans", layer: "primitive" },
  { name: "--footer-height", layer: "primitive" },
  { name: "--gutter", layer: "primitive" },
  { name: "--info", layer: "semantic" },
  { name: "--info-light", layer: "semantic" },
  { name: "--info-text", layer: "semantic" },
  { name: "--motion-base", layer: "primitive" },
  { name: "--motion-fast", layer: "primitive" },
  { name: "--motion-slow", layer: "primitive" },
  { name: "--primary", layer: "semantic" },
  { name: "--primary-hover", layer: "semantic" },
  { name: "--primary-light", layer: "semantic" },
  { name: "--primary-press", layer: "semantic" },
  { name: "--primary-text", layer: "semantic" },
  { name: "--radius-full", layer: "primitive" },
  { name: "--radius-lg", layer: "primitive" },
  { name: "--radius-md", layer: "primitive" },
  { name: "--radius-sm", layer: "primitive" },
  { name: "--radius-xl", layer: "primitive" },
  { name: "--row-h", layer: "primitive" },
  { name: "--segment-active-bg", layer: "component" },
  { name: "--shadow-focus", layer: "semantic" },
  { name: "--shadow-lg", layer: "semantic" },
  { name: "--shadow-md", layer: "semantic" },
  { name: "--shadow-sm", layer: "semantic" },
  { name: "--shadow-xs", layer: "semantic" },
  { name: "--shell-bg", layer: "component" },
  { name: "--shell-bg-elevated", layer: "component" },
  { name: "--shell-border", layer: "component" },
  { name: "--shell-height", layer: "primitive" },
  { name: "--shell-item-active", layer: "component" },
  { name: "--shell-item-hover", layer: "component" },
  { name: "--shell-text", layer: "component" },
  { name: "--shell-text-secondary", layer: "component" },
  { name: "--sidenav-current-width", layer: "component" },
  { name: "--sidenav-width", layer: "primitive" },
  { name: "--sidenav-width-collapsed", layer: "primitive" },
  { name: "--space-1", layer: "primitive" },
  { name: "--space-10", layer: "primitive" },
  { name: "--space-12", layer: "primitive" },
  { name: "--space-16", layer: "primitive" },
  { name: "--space-2", layer: "primitive" },
  { name: "--space-3", layer: "primitive" },
  { name: "--space-4", layer: "primitive" },
  { name: "--space-5", layer: "primitive" },
  { name: "--space-6", layer: "primitive" },
  { name: "--space-8", layer: "primitive" },
  { name: "--step-0", layer: "primitive" },
  { name: "--step-00", layer: "primitive" },
  { name: "--step-1", layer: "primitive" },
  { name: "--step-2", layer: "primitive" },
  { name: "--step-3", layer: "primitive" },
  { name: "--step-4", layer: "primitive" },
  { name: "--success", layer: "semantic" },
  { name: "--success-light", layer: "semantic" },
  { name: "--success-text", layer: "semantic" },
  { name: "--tenure-amber-300", layer: "primitive" },
  { name: "--tenure-amber-400", layer: "primitive" },
  { name: "--tenure-amber-50", layer: "primitive" },
  { name: "--tenure-amber-600", layer: "primitive" },
  { name: "--tenure-amber-700", layer: "primitive" },
  { name: "--tenure-amber-800", layer: "primitive" },
  { name: "--tenure-amber-a15", layer: "primitive" },
  { name: "--tenure-amber-a16", layer: "primitive" },
  { name: "--tenure-berry-400", layer: "primitive" },
  { name: "--tenure-berry-500", layer: "primitive" },
  { name: "--tenure-black", layer: "primitive" },
  { name: "--tenure-black-a72", layer: "primitive" },
  { name: "--tenure-blue-300", layer: "primitive" },
  { name: "--tenure-blue-400", layer: "primitive" },
  { name: "--tenure-blue-50", layer: "primitive" },
  { name: "--tenure-blue-500", layer: "primitive" },
  { name: "--tenure-blue-600", layer: "primitive" },
  { name: "--tenure-blue-a15", layer: "primitive" },
  { name: "--tenure-forest-200", layer: "primitive" },
  { name: "--tenure-forest-25", layer: "primitive" },
  { name: "--tenure-forest-300", layer: "primitive" },
  { name: "--tenure-forest-350", layer: "primitive" },
  { name: "--tenure-forest-400", layer: "primitive" },
  { name: "--tenure-forest-50", layer: "primitive" },
  { name: "--tenure-forest-500", layer: "primitive" },
  { name: "--tenure-forest-550", layer: "primitive" },
  { name: "--tenure-forest-600", layer: "primitive" },
  { name: "--tenure-forest-650", layer: "primitive" },
  { name: "--tenure-forest-700", layer: "primitive" },
  { name: "--tenure-forest-750", layer: "primitive" },
  { name: "--tenure-forest-800", layer: "primitive" },
  { name: "--tenure-forest-850", layer: "primitive" },
  { name: "--tenure-forest-900", layer: "primitive" },
  { name: "--tenure-forest-950", layer: "primitive" },
  { name: "--tenure-forest-a14", layer: "primitive" },
  { name: "--tenure-forest-a16", layer: "primitive" },
  { name: "--tenure-ink-900", layer: "primitive" },
  { name: "--tenure-ink-a05", layer: "primitive" },
  { name: "--tenure-ink-a08", layer: "primitive" },
  { name: "--tenure-ink-a50", layer: "primitive" },
  { name: "--tenure-navy-50", layer: "primitive" },
  { name: "--tenure-navy-700", layer: "primitive" },
  { name: "--tenure-navy-800", layer: "primitive" },
  { name: "--tenure-navy-850", layer: "primitive" },
  { name: "--tenure-orange-400", layer: "primitive" },
  { name: "--tenure-orange-500", layer: "primitive" },
  { name: "--tenure-paper-100", layer: "primitive" },
  { name: "--tenure-paper-150", layer: "primitive" },
  { name: "--tenure-paper-200", layer: "primitive" },
  { name: "--tenure-paper-25", layer: "primitive" },
  { name: "--tenure-paper-250", layer: "primitive" },
  { name: "--tenure-paper-300", layer: "primitive" },
  { name: "--tenure-paper-400", layer: "primitive" },
  { name: "--tenure-paper-450", layer: "primitive" },
  { name: "--tenure-paper-50", layer: "primitive" },
  { name: "--tenure-paper-600", layer: "primitive" },
  { name: "--tenure-red-300", layer: "primitive" },
  { name: "--tenure-red-400", layer: "primitive" },
  { name: "--tenure-red-450", layer: "primitive" },
  { name: "--tenure-red-50", layer: "primitive" },
  { name: "--tenure-red-500", layer: "primitive" },
  { name: "--tenure-red-600", layer: "primitive" },
  { name: "--tenure-red-700", layer: "primitive" },
  { name: "--tenure-red-a15", layer: "primitive" },
  { name: "--tenure-red-a16", layer: "primitive" },
  { name: "--tenure-slate-100", layer: "primitive" },
  { name: "--tenure-slate-150", layer: "primitive" },
  { name: "--tenure-slate-200", layer: "primitive" },
  { name: "--tenure-slate-25", layer: "primitive" },
  { name: "--tenure-slate-250", layer: "primitive" },
  { name: "--tenure-slate-300", layer: "primitive" },
  { name: "--tenure-slate-350", layer: "primitive" },
  { name: "--tenure-slate-400", layer: "primitive" },
  { name: "--tenure-slate-450", layer: "primitive" },
  { name: "--tenure-slate-500", layer: "primitive" },
  { name: "--tenure-slate-520", layer: "primitive" },
  { name: "--tenure-slate-560", layer: "primitive" },
  { name: "--tenure-slate-600", layer: "primitive" },
  { name: "--tenure-slate-650", layer: "primitive" },
  { name: "--tenure-slate-700", layer: "primitive" },
  { name: "--tenure-slate-750", layer: "primitive" },
  { name: "--tenure-slate-800", layer: "primitive" },
  { name: "--tenure-slate-820", layer: "primitive" },
  { name: "--tenure-slate-850", layer: "primitive" },
  { name: "--tenure-slate-870", layer: "primitive" },
  { name: "--tenure-slate-880", layer: "primitive" },
  { name: "--tenure-slate-890", layer: "primitive" },
  { name: "--tenure-slate-900", layer: "primitive" },
  { name: "--tenure-slate-930", layer: "primitive" },
  { name: "--tenure-slate-940", layer: "primitive" },
  { name: "--tenure-slate-960", layer: "primitive" },
  { name: "--tenure-slate-a14", layer: "primitive" },
  { name: "--tenure-slate-a15", layer: "primitive" },
  { name: "--tenure-teal-400", layer: "primitive" },
  { name: "--tenure-teal-500", layer: "primitive" },
  { name: "--tenure-violet-400", layer: "primitive" },
  { name: "--tenure-violet-600", layer: "primitive" },
  { name: "--tenure-white", layer: "primitive" },
  { name: "--tenure-white-a05", layer: "primitive" },
  { name: "--tenure-white-a07", layer: "primitive" },
  { name: "--tenure-white-a09", layer: "primitive" },
  { name: "--text-1", layer: "semantic" },
  { name: "--text-2", layer: "semantic" },
  { name: "--text-3", layer: "semantic" },
  { name: "--text-disabled", layer: "semantic" },
  { name: "--text-inverse", layer: "semantic" },
  { name: "--text-link", layer: "semantic" },
  { name: "--warning", layer: "semantic" },
  { name: "--warning-light", layer: "semantic" },
  { name: "--warning-text", layer: "semantic" },
  { name: "--z-assist", layer: "primitive" },
  { name: "--z-assist-scrim", layer: "primitive" },
  { name: "--z-chrome-popover", layer: "primitive" },
  { name: "--z-dragged", layer: "primitive" },
  { name: "--z-header", layer: "primitive" },
  { name: "--z-marker", layer: "primitive" },
  { name: "--z-nav", layer: "primitive" },
  { name: "--z-overlay", layer: "primitive" },
  { name: "--z-popover", layer: "primitive" },
  { name: "--z-raised", layer: "primitive" },
  { name: "--z-scrim", layer: "primitive" },
  { name: "--z-skip-link", layer: "primitive" },
  { name: "--z-sticky", layer: "primitive" },
  { name: "--z-toast", layer: "primitive" },
] as const satisfies readonly TokenEntry[]

/** Every token name the stylesheet declares, as a compile-time union. */
export type TokenName = (typeof TOKENS)[number]["name"]

/**
 * The `var()` reference for a token, checked against the catalog at compile time.
 *
 * This is what makes the catalog load-bearing rather than documentation: a
 * consumer writes `cssVar("--chart-1")` and a rename in the stylesheet — which
 * regenerates this file — turns that call site red.
 */
export function cssVar(name: TokenName): string {
  return `var(${name})`
}

/** The tier a token belongs to, or undefined when it is not in the catalog. */
export function layerOf(name: string): TokenLayer | undefined {
  return TOKENS.find((token) => token.name === name)?.layer
}
